[package]
name = "nats-s3-connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-nats = "0.32.1"
aws-config = "1.0.1"
aws-sdk-s3 = "0.39.1"
axum = "0.7.1"
axum-macros = "0.2.3"
bincode = "1.3.3"
bytes = "1.5.0"
clap = { version = "4.4.6", features = ["derive"] }
hyper = "1.0.1"
futures = "0.3.28"
lazy_static = "1.4.0"
rust-s3 = "0.34.0-rc1"
serde = "1.0.193"
serde_json = "1.0"
sha2 = "0.10.8"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.3.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
hyper-util = "0.1.1"
figment = { version = "0.10.12", features = ["env", "toml", "yaml"]}
