[package]
name = "nats-s3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-nats = "0.32.1"
aws-config = "1.0.1"
aws-sdk-s3 = "0.39.1"
bincode = "1.3.3"
bytes = "1.5.0"
clap = { version = "4.4.6", features = ["derive"] }
futures = "0.3.28"
lazy_static = "1.4.0"
rust-s3 = "0.34.0-rc1"
serde = "1.0.193"
sha2 = "0.10.8"
tokio = { version = "1", features = ["full"] }
