log = "info"

[server]
addr = "0.0.0.0:8080"

[nats]
url = "localhost:4222"

[s3]
region = "us-east-1"
endpoint = "http://localhost:9000"
access_key = "test-user"
secret_key = "test-password"

[[store]]
name ="job1"
stream = "test-stream"
subject = "subjects-1"
bucket = "bucket-demo-1"

[[store]]
name ="job2"
stream = "test-stream"
subject = "subjects-2"
bucket = "bucket-demo-2"
